services:
    bot:
        container_name: bot
        image: bot:latest
        build:
            context: .
            dockerfile: ./apps/bot/Dockerfile
            args:
                - CONCURRENCY=${CONCURRENCY:-5}
        environment:
            - TZ: "Europe/Lisbon"
        volumes:
            - ~/shared:/usr/src/shared
        restart: always
