name: Continuous deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy bot application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          set -e
          echo "SB_CLIENT__TOKEN=${{ secrets.SB_CLIENT__TOKEN }}" >> .env
          echo "SB_SERVICES__MONGODB__URI=${{ secrets.SB_SERVICES__MONGODB__URI }}" >> .env
          echo "SB_SERVICES__REDIS__URI=${{ secrets.SB_SERVICES__REDIS__URI }}" >> .env
          echo "SB_SERVICES__PICOVOICE__API_KEY=${{ secrets.SB_SERVICES__PICOVOICE__API_KEY }}" >> .env
          echo "SB_SERVICES__STEAM__API_KEY=${{ secrets.SB_SERVICES__STEAM__API_KEY }}" >> .env
          echo "SB_SERVICES__XBOX__API_KEY=${{ secrets.SB_SERVICES__XBOX__API_KEY }}" >> .env
          echo "SB_SERVICES__ITAD__API_KEY=${{ secrets.SB_SERVICES__ITAD__API_KEY }}" >> .env
          echo "SB_SERVICES__IGDB__CLIENT_ID=${{ secrets.SB_SERVICES__IGDB__CLIENT_ID }}" >> .env
          echo "SB_SERVICES__IGDB__CLIENT_SECRET=${{ secrets.SB_SERVICES__IGDB__CLIENT_SECRET }}" >> .env
          echo "SB_SERVICES__TMDB__API_KEY=${{ secrets.SB_SERVICES__TMDB__API_KEY }}" >> .env
          echo "SB_SERVICES__ANIME_SCHEDULE__API_KEY=${{ secrets.SB_SERVICES__ANIME_SCHEDULE__API_KEY }}" >> .env
          echo "SB_SERVICES__GOOGLE__CREDENTIALS__PATH=${{ secrets.SB_SERVICES__GOOGLE__CREDENTIALS__PATH }}" >> .env
          cd ~/serpine-bot
          git pull origin master
          docker compose --env-file ~/.env up --build --force-recreate --no-deps -d bot
          docker system prune -f
          rm ~/.env
