name: SerpineBot deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy bot application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          set -e
          for secret_name in $(jq -r 'keys[]' <<< "${{ toJson(secrets) }}"); do
            echo "$secret_name=${{ secrets.[secret_name] }}" >> .env
          done
          cd ~/serpine-bot
          git pull origin master
          echo "SB_SERVICES__ITAD__API_KEY=${{ secrets.SB_SERVICES__ITAD__API_KEY }}"
          docker compose --env-file ~/.env up --build --force-recreate --no-deps -d bot
          docker system prune -f
          rm ~/.env
